#ifndef REMA_MOUSEBUTTONCODEDEFINITIONS_H
#define REMA_MOUSEBUTTONCODEDEFINITIONS_H

// From glfw3.h
#define REMA_MOUSE_BUTTON_1         0
#define REMA_MOUSE_BUTTON_2         1
#define REMA_MOUSE_BUTTON_3         2
#define REMA_MOUSE_BUTTON_4         3
#define REMA_MOUSE_BUTTON_5         4
#define REMA_MOUSE_BUTTON_6         5
#define REMA_MOUSE_BUTTON_7         6
#define REMA_MOUSE_BUTTON_8         7
#define REMA_MOUSE_BUTTON_LAST      REMA_MOUSE_BUTTON_8
#define REMA_MOUSE_BUTTON_LEFT      REMA_MOUSE_BUTTON_1
#define REMA_MOUSE_BUTTON_RIGHT     REMA_MOUSE_BUTTON_2
#define REMA_MOUSE_BUTTON_MIDDLE    REMA_MOUSE_BUTTON_3

#endif // !REMA_MOUSEBUTTONCODEDEFINITIONS_H

